# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/andreoliwa/nitpick
    # TODO: pin to a tag when a new nitpick version is released
    # https://github.com/andreoliwa/nitpick/commit/5e98e5fcda32d1fe40939bf3abd4e6e5da00e9ba
    rev: ed4c4adf0450d90855b75d6a1d63e8f370faf983
    hooks:
      - id: nitpick-run
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.0
    hooks:
      - id: prettier
        stages: [commit]
  - repo: https://github.com/commitizen-tools/commitizen
    hooks:
      - id: commitizen
        stages:
          - commit-msg
    rev: v2.20.0

# https://pre-commit.ci/#configuration
ci:
  skip: [nitpick-run]
