name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Clippy
        run: cargo clippy
      - name: Run tests
        shell: bash
        run: RUST_BACKTRACE=full cargo test --verbose
      - name: Formatting
        run: cargo fmt -- --check
  release:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2
      - name: Create bump and changelog
        # After commitizen can bump Cargo.lock files, rever this to their own implementation
        uses: jaysonsantos/commitizen-action@custom-commitizen-install
        with:
          github_token: ${{ secrets.GH_PERSONAL_TOKEN }}
          branch: main
          changelog_increment_filename: body.md
          custom_commitzen_install: "https://github.com/jaysonsantos/commitizen/archive/refs/heads/version-in-random-position.zip#egg=commitizen"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: "body.md"
          tag_name: ${{ env.REVISION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }}
